#!/usr/bin/python

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from database import get_db
from models import Order, product
from schemas import OrderCreate, OrderResponse

router = APIRouter()

@router.get("/")
def get_orders(db: Session = Depends(get_db)):
    return db.query(Order).all()


@router.post("/", response_model=OrderResponse)
def create_order(order: OrderCreate, db: Session = Depends(get_db)):
    product = db.query(Product).filter(Product.id == order.product_id).first()
    total_price = product.price * order.quantity
    new_order = Order(
        user_id=order.user_id,
        product_id=order.product_id,
        quantity=order.quantity,
        total_price=total_price,
    )
    db.add(new_order)
    db.commit()
    db.refresh(new_order)
    return new_order
