#!/usr/bin/python

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from database import get_db
from models import Order

router = APIRouter()

@router.get("/")
def get_orders(db: Session = Depends(get_db)):
    return db.query(Order).all()
