#!/usr/bin/python

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from database import get_db
from models import Product

router = APIRouter()

@router.get("/")
def get_products(db: Session = Depends(get_db)):
    return db.query(Product).all()

@router.post("/")
def create_product(name: str, description: str, price: float, db: Session = Depends(get_db)):
    product = Product(name=name, description=description, price=price)
    db.add(product)
    db.commit()
    return {"message": "Product created"}
