#!/usr/bin/python 

from stripe_payment import router as stripe_router
from fastapi import FastAPI
from routes import users, products, orders
from database import engine, Base

app = FastAPI(title="Buy & Sell API", version="1.0")
app.include_router(stripe_router, prefix="/payment", tags=["Payment"])

# Create database tables
Base.metadata.create_all(bind=engine)

# Include Routes
app.include_router(users.router, prefix="/users", tags=["Users"])
app.include_router(products.router, prefix="/products", tags=["Products"])
app.include_router(orders.router, prefix="/orders", tags=["Orders"])

@app.get("/")
def home():
    return {"message": "Welcome to Buy & Sell API!"}
